excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sbussmann.github.io
title: Fun with Analytics
tagline: Predicting the Past, Present, and Future
description: My perspective on exciting topics.
paginate: 5
